# 📡👥📱Customer Churn Analysis in Telecom Using Behavioral Data

In [4]:
# librerías
import pandas as pds

In [5]:
# Cargar el dataset
df = pds.read_csv("../data/telecom_churn_data.csv")

df.head()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,last_date_of_month_9,arpu_6,...,sachet_3g_9,fb_user_6,fb_user_7,fb_user_8,fb_user_9,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g,sep_vbc_3g
0,7000842753,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,197.385,...,0,1.0,1.0,1.0,NaN,968,30.4,0.0,101.20,3.58
1,7001865778,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,34.047,...,0,NaN,1.0,1.0,NaN,1006,0.0,0.0,0.00,0.00
2,7001625959,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,167.690,...,0,NaN,NaN,NaN,1.0,1103,0.0,0.0,4.17,0.00
3,7001204172,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,221.338,...,0,NaN,NaN,NaN,NaN,2491,0.0,0.0,0.00,0.00
4,7000142493,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,261.636,...,0,0.0,NaN,NaN,NaN,1526,0.0,0.0,0.00,0.00

In [6]:
# Tipo de datos
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Columns: 226 entries, mobile_number to sep_vbc_3g
dtypes: float64(179), int64(35), str(12)
memory usage: 172.4 MB

In [7]:
# tipos de datos por columna
df.dtypes

mobile_number       int64
circle_id           int64
loc_og_t2o_mou    float64
std_og_t2o_mou    float64
loc_ic_t2o_mou    float64
                   ...
aon                 int64
aug_vbc_3g        float64
jul_vbc_3g        float64
jun_vbc_3g        float64
sep_vbc_3g        float64
Length: 226, dtype: object

In [8]:
# lista de columnas a conservar
cols_keep = [
    # 💰 Dinero
    "arpu_6", "arpu_7", "arpu_8", "arpu_9",
    "total_rech_amt_6", "total_rech_amt_7", "total_rech_amt_8", "total_rech_amt_9",
    
    # 📞 Uso
    "total_og_mou_6", "total_og_mou_7", "total_og_mou_8", "total_og_mou_9",
    "total_ic_mou_6", "total_ic_mou_7", "total_ic_mou_8", "total_ic_mou_9",
    
    # 📡 Datos móviles
    "vol_2g_mb_6", "vol_2g_mb_7", "vol_2g_mb_8", "vol_2g_mb_9",
    "vol_3g_mb_6", "vol_3g_mb_7", "vol_3g_mb_8", "vol_3g_mb_9",
    
    # 📆 Actividad
    "total_rech_num_6", "total_rech_num_7", "total_rech_num_8", "total_rech_num_9",
    "aon",
]

# Crear un nuevo DataFrame solo con esas columnas
df_filtrado = df[cols_keep]

# Verificar
print(df_filtrado.head())

    arpu_6   arpu_7   arpu_8   arpu_9  total_rech_amt_6  total_rech_amt_7  \
0  197.385  214.816  213.803   21.100               362               252
1   34.047  355.074  268.321   86.285                74               384
2  167.690  189.058  210.226  290.714               168               315
3  221.338  251.102  508.054  389.500               230               310
4  261.636  309.876  238.174  163.426               196               350

   total_rech_amt_8  total_rech_amt_9  total_og_mou_6  total_og_mou_7  ...  \
0               252                 0            0.00            0.00  ...
1               283               121           40.31          178.53  ...
2               116               358          155.33          412.94  ...
3               601               410          223.23          135.31  ...
4               287               200          127.28          241.33  ...

   vol_2g_mb_9  vol_3g_mb_6  vol_3g_mb_7  vol_3g_mb_8  vol_3g_mb_9  \
0          0.0        83.57       150.76       109.61         0.00
1          0.0         0.00         0.00         0.00         0.00
2          0.0         0.00         0.00         0.00         8.42
3          0.0         0.00         0.00         0.00         0.00
4          0.0         0.00         0.00         0.00         0.00

   total_rech_num_6  total_rech_num_7  total_rech_num_8  total_rech_num_9  \
0                 4                 3                 2                 6
1                 4                 9                11                 5
2                 5                 4                 2                 7
3                10                11                18                14
4                 5                 6                 3                 4

    aon
0   968
1  1006
2  1103
3  2491
4  1526

[5 rows x 29 columns]

In [9]:
# definir churn en base a actividad del mes 9
df_filtrado['churn'] = (
    (df_filtrado['total_rech_amt_9'] == 0) &
    (df_filtrado['total_og_mou_9'] == 0) &
    (df_filtrado['total_ic_mou_9'] == 0) &
    (df_filtrado['vol_2g_mb_9'] == 0) &
    (df_filtrado['vol_3g_mb_9'] == 0)
).astype(int)

# revisar distribución
print(df_filtrado['churn'].value_counts())

churn
0    91041
1     8958
Name: count, dtype: int64

In [10]:
# valores faltantes
df_filtrado.isnull().sum().sort_values(ascending=False)

arpu_6              0
arpu_7              0
aon                 0
total_rech_num_9    0
total_rech_num_8    0
total_rech_num_7    0
total_rech_num_6    0
vol_3g_mb_9         0
vol_3g_mb_8         0
vol_3g_mb_7         0
vol_3g_mb_6         0
vol_2g_mb_9         0
vol_2g_mb_8         0
vol_2g_mb_7         0
vol_2g_mb_6         0
total_ic_mou_9      0
total_ic_mou_8      0
total_ic_mou_7      0
total_ic_mou_6      0
total_og_mou_9      0
total_og_mou_8      0
total_og_mou_7      0
total_og_mou_6      0
total_rech_amt_9    0
total_rech_amt_8    0
total_rech_amt_7    0
total_rech_amt_6    0
arpu_9              0
arpu_8              0
churn               0
dtype: int64

In [11]:
# registros duplicados
df_filtrado.duplicated().sum()

np.int64(0)

In [12]:
# distribución porcentual de clientes que permanecen o abandonan (churn)
df_filtrado['churn'].value_counts(normalize=True)

churn
0    0.910419
1    0.089581
Name: proportion, dtype: float64

In [13]:
# promedio de recargas en el mes 8 según si el cliente hizo churn o no
df_filtrado.groupby('churn')['total_rech_amt_8'].mean()

churn
0    346.520842
1     96.872516
Name: total_rech_amt_8, dtype: float64

In [14]:
# promedio de llamadas salientes en el mes 8 según churn
df_filtrado.groupby('churn')['total_og_mou_8'].mean()

churn
0    326.079428
1     80.938816
Name: total_og_mou_8, dtype: float64

In [15]:
# promedio de consumo de datos 2G en el mes 8 según churn
df_filtrado.groupby('churn')['vol_2g_mb_8'].mean()

churn
0    53.994882
1    11.299081
Name: vol_2g_mb_8, dtype: float64

#### **insight:** Los clientes en riesgo muestran señales claras de abandono antes de irse, lo que abre oportunidad para estrategias de retención anticipadas.

In [16]:
df_filtrado.groupby('churn')[[
    'total_rech_amt_6',
    'total_rech_amt_7',
    'total_rech_amt_8'
]].mean()

       total_rech_amt_6  total_rech_amt_7  total_rech_amt_8
churn
0            326.324019        332.257785        346.520842
1            339.614758        228.498884         96.872516

#### early warning signal (señal temprana de abando)

In [17]:
# uso
df_filtrado.groupby('churn')[[
    'total_og_mou_6',
    'total_og_mou_7',
    'total_og_mou_8'
]].mean()

       total_og_mou_6  total_og_mou_7  total_og_mou_8
churn
0          301.472797      318.058976      326.079428
1          342.336722      230.676496       80.938816

### **insight:** Clientes valiosos pueden convertirse en churn si su actividad cae rápidamente

In [18]:
df_filtrado['caida_rech'] = df_filtrado['total_rech_amt_8'] - df_filtrado['total_rech_amt_6']
df_filtrado.groupby('churn')['caida_rech'].mean()

churn
0     20.196823
1   -242.742242
Name: caida_rech, dtype: float64

#### **insight:** Los clientes que hacen churn presentan una caída promedio de más de 240 unidades en recargas respecto a meses anteriores, mientras que los clientes activos mantienen o incrementan su consumo.

In [19]:
for x in [-50, -100, -150, -200]:
    df_filtrado['riesgo'] = (df_filtrado['caida_rech'] < x).astype(int)
    print(f"Umbral {x}")
    print(df_filtrado.groupby('riesgo')['churn'].mean())
    print("-----")

Umbral -50
riesgo
0    0.043266
1    0.166308
Name: churn, dtype: float64
-----
Umbral -100
riesgo
0    0.045914
1    0.194823
Name: churn, dtype: float64
-----
Umbral -150
riesgo
0    0.052814
1    0.218028
Name: churn, dtype: float64
-----
Umbral -200
riesgo
0    0.058930
1    0.235844
Name: churn, dtype: float64
-----

#### **insight:** Se identificó que clientes con una caída superior a 150 unidades en recargas presentan más de 4 veces la probabilidad de churn en comparación con clientes sin caída significativa.

In [20]:
df_filtrado['riesgo_final'] = (df_filtrado['caida_rech'] < -150).astype(int)
# df_filtrado.to_csv("churn_limpio.csv", index=False)

In [21]:
# estadísticas descriptivas
df_filtrado.describe()

,arpu_6,arpu_7,arpu_8,arpu_9,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,total_rech_amt_9,total_og_mou_6,total_og_mou_7,...,vol_3g_mb_9,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_num_9,aon,churn,caida_rech,riesgo,riesgo_final
count,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,...,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000
mean,282.987358,278.536648,279.154731,261.645069,327.514615,322.962970,324.157122,303.345673,305.133424,310.231175,...,136.056613,7.558806,7.700367,7.212912,6.893019,1219.854749,0.089581,-3.357494,0.173252,0.222542
std,328.439770,338.156291,344.474791,341.998630,398.019701,408.114237,416.540455,404.588583,463.419481,480.031178,...,577.394194,7.078405,7.070422,7.203753,7.096261,954.733842,0.285582,355.856154,0.378467,0.415955
min,-2258.709000,-2014.045000,-945.808000,-1899.505000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,180.000000,0.000000,-12000.000000,0.000000,0.000000
25%,93.411500,86.980500,84.126000,62.685000,109.000000,100.000000,90.000000,52.000000,44.740000,43.010000,...,0.000000,3.000000,3.000000,3.000000,3.000000,467.000000,0.000000,-130.000000,0.000000,0.000000
50%,197.704000,191.640000,192.080000,176.849000,230.000000,220.000000,225.000000,200.000000,145.140000,141.530000,...,0.000000,6.000000,6.000000,5.000000,5.000000,863.000000,0.000000,0.000000,0.000000,0.000000
75%,371.060000,365.344500,369.370500,353.466500,437.500000,428.000000,434.500000,415.000000,372.860000,378.570000,...,0.000000,9.000000,10.000000,9.000000,9.000000,1807.500000,0.000000,130.000000,0.000000,0.000000
max,27731.088000,35145.834000,33543.624000,38805.617000,35190.000000,40335.000000,45320.000000,37235.000000,10674.030000,11365.310000,...,39221.270000,307.000000,138.000000,196.000000,131.000000,4337.000000,1.000000,15210.000000,1.000000,1.000000

In [22]:
# Guardar el archivo csv filtrado
df_filtrado.to_csv("../data/clean_churn.csv", index=False)